#
#  Inventory file for the development Vagrant / Docker Swarm
#
devl_swarm:
  vars:
    ansible_host: localhost 
    ansible_user: vagrant

  children:
    managers:
      hosts:
        devl-manager-1:
          ansible_port: 2222
          ansible_ssh_private_key_file: /Users/jeff/.ssh/devl-manager-1

    workers:
      hosts:
        devl-worker-1:
          ansible_port: 2200
          ansible_ssh_private_key_file: /Users/jeff/.ssh/devl-worker-1
        devl-worker-2:
          ansible_port: 2201
          ansible_ssh_private_key_file: /Users/jeff/.ssh/devl-worker-2

