---

- name: Maintain python versions 

  hosts: "{{ HOSTS }}"

  vars:
    install_version: 3.13.0
    remove_version: 3.8.0

  roles:
    - role: staticdev.pyenv
      vars:
        pyenv_version: "v2.4.15"  # from https://github.com/pyenv/pyenv/releases
        pyenv_env: user
        pyenv_path: "{{ ansible_env.HOME }}/.pyenv"
        pyenv_enable_autocompletion: false
        pyenv_global:
          - 3.12.7
        pyenv_python_versions:
          - 3.12.7

  tasks:
    - name: Install python version
      ansible.builtin.command: "pyenv install {{ install_version }}"
      args:
        creates: ~/.pyenv/versions/{{ install_version }}

    - name: Remove python version
      ansible.builtin.command: "pyenv uninstall {{ remove_version }}"
      args:
        removes: ~/.pyenv/versions/{{ remove_version }}

...
