---

- name: Ensure my standard group ids are set
  become: true
  gather_facts: false
  hosts: prod_swarm

  tasks:
    - name: Ensure the group 'jeff' exists
      ansible.builtin.group:
        name: jeff
        gid: 10000
        state: present
...
