---

- name: Configure my userid the way I like it
  become: true
  gather_facts: false
  hosts: all

  tasks:
    - name: Ensure the group 'jeff' exists
      ansible.builtin.group:
        name: jeff
        state: present
        gid: 10000

    - name: Ensure my userid exists
      ansible.builtin.user:
        name: jeff
        group: jeff
        comment: Jeffs standard userid maintained by Ansible
        state: present
        shell: /bin/bash
        # uid: 10000
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ ansible_host }}_rsa

...
