---

- name: Ensure my standard id is created and configured
  become: true
  gather_facts: false
  hosts: all

  tasks:
    - name: Ensure the group 'jeff' exists
      ansible.builtin.group:
        name: jeff
        gid: 10000
        state: present

    - name: Ensure the user 'jeff' exists
      ansible.builtin.user:
        name: jeff
        group: jeff
        comment: Jeffs standard userid maintained by Ansible
        state: present
        shell: /bin/bash
        uid: 10000
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ ansible_host }}_rsa

    - name: Ensure 'jeff' can run any command without typing 'sudo'
      community.general.sudoers:
        commands: ALL
        name: ALL_jeff
        user: jeff
...
